; (define current-time 0)
; (define (render dt)
;     (set! current-time (+ dt current-time))
;     (let (
;         (mx (floor (/ current-time 10)))
;     )
;         (if (> mx 1280.0)
;             (set! current-time 0)
;         )
;         (clear-screen 0 0 0)
;         (set-color mx 255 128)
;         (draw-rect (list (+ 20 mx) 20 220 250))
;         (set-color 128 255 64)
;         (draw-rect (list 300 300 220 250))
;     )
; )
; (game render)
(define current-time 0)
(define tx 0.0)
(define tex)
(define rect_1 (rectangle 0 0 16 16))
(define (on-load)
    (set! tex (texture->load "test.png"))
    (display "Texture: ") 
    (display (texture->width tex))
    (display " : ")
    (display (texture->height tex))
    (display "\n")
)
(define (render)
    (draw-text "Hello from Scheme!" (inexact->exact (+ 10 tx)) 200 20 (color->rgb 255 0 255))
    (texture->draw tex 8 8)
)
(define (update dt)
    (set! current-time (+ dt current-time))
    (set! tx (floor (/ current-time 0.25)))
)
(game 800 600 "Tinkerboy with Raylib" on-load update render)
(texture->unload tex)